spring:
  application:
    name: GeminiDocumentStandardizerApi

  mvc:
    locale:
      resolver:
        fixed
      locale:
        pt_BR

  jpa:
    show-sql:
      true
    properties:
      hibernate:
        format_sql:
          false
        ddl-auto:
          update

  datasource:
    driverClassName:
      com.mysql.cj.jdbc.Driver
    url:
      jdbc:mysql://localhost:3306/standardizerbank?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
    username:
      root
    password:
      root