spring:
  application:
    name: GeminiDocumentStandardizerApi

  mvc:
    locale-resolver: fixed
    locale: pt_BR

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/standardizerbank?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
    username: root
    password: root

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent?key=
    key: ${GEMINI_API_KEY}